"use client";
import { GoogleOAuthProvider } from "@react-oauth/google";
import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <GoogleOAuthProvider clientId="383625496778-qm34fmrbdtf08i78mn1qv960cb8urcvc.apps.googleusercontent.com">
        <body className={inter.className}>
          <Toaster />
          {children}
        </body>
      </GoogleOAuthProvider>
    </html>
  );
}
